name: Compose full changelog

on:
  release:
    types: [created, edited]

env:
  CHANGELOG_ARTIFACTS: changelog

jobs:
  create-changelog:
    if: github.repository == 'arduino/arduino-ide'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Tag
        id: tag_name
        run: |
          echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Create full changelog
        id: full-changelog
        run: |
          mkdir "${{ github.workspace }}/${{ env.CHANGELOG_ARTIFACTS }}"

          # Get the changelog file name to build
          CHANGELOG_FILE_NAME="${{ steps.tag_name.outputs.TAG_NAME }}-$(date --iso-8601=s).md"

          # Create manifest file pointing to latest changelog file name
          echo "$CHANGELOG_FILE_NAME" >> "${{ github.workspace }}/${{ env.CHANGELOG_ARTIFACTS }}/latest.txt"

          # Compose changelog
          yarn run compose-changelog "${{ github.workspace }}/${{ env.CHANGELOG_ARTIFACTS }}/$CHANGELOG_FILE_NAME"

      - name: Publish Changelog [S3]
        uses: docker://plugins/s3
        env:
          PLUGIN_SOURCE: '${{ env.CHANGELOG_ARTIFACTS }}/*'
          PLUGIN_STRIP_PREFIX: '${{ env.CHANGELOG_ARTIFACTS }}/'
          PLUGIN_TARGET: '/arduino-ide/changelog'
          PLUGIN_BUCKET: ${{ secrets.DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
